# Generated by Django 5.2.16 on 2026-07-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuvePrincipale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.FloatField(verbose_name='Capacité (Litres)')),
            ],
            options={
                'verbose_name': 'Cuve Principale',
                'verbose_name_plural': 'Cuves Principales',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='CuveJournaliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.FloatField(verbose_name='Capacité (Litres)')),
                ('cuve_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_journalieres', to='dashboard.cuveprincipale', verbose_name='Cuve Principale')),
            ],
            options={
                'verbose_name': 'Cuve Journalière',
                'verbose_name_plural': 'Cuves Journalières',
            },
        ),
        migrations.CreateModel(
            name='GroupeElectrogene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compteur_horaire', models.FloatField(default=0.0, verbose_name='Compteur horaire (heures)')),
                ('consommation_horaire', models.FloatField(default=0.0, verbose_name='Consommation horaire (L/h)')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('puissance', models.CharField(blank=True, max_length=50, verbose_name='Puissance (ex: 250kVA)')),
                ('cuves_journalieres', models.ManyToManyField(blank=True, related_name='groupes_electrogenes', to='dashboard.cuvejournaliere', verbose_name='Cuves journalières associées')),
            ],
            options={
                'verbose_name': 'Groupe Électrogène',
                'verbose_name_plural': 'Groupes Électrogènes',
            },
        ),
        migrations.CreateModel(
            name='LigneRapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_gasoil_cuve_principale', models.FloatField(default=0.0, verbose_name='Qté Gasoil Cuve Principale (L)')),
                ('quantite_gasoil_cuve_journaliere', models.FloatField(default=0.0, verbose_name='Qté Gasoil Cuve Journalière (L)')),
                ('compteur_horaire', models.FloatField(default=0.0, verbose_name='Compteur horaire (h)')),
                ('depotage', models.FloatField(default=0.0, verbose_name='Dépotage (L)')),
                ('etat_fonctionnement', models.CharField(default='F', max_length=50, verbose_name='État de fonctionnement')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('cuve_journaliere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport', to='dashboard.cuvejournaliere')),
                ('cuve_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport', to='dashboard.cuveprincipale')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport', to='dashboard.groupeelectrogene')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dashboard.rapport', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Ligne de Rapport',
                'verbose_name_plural': 'Lignes de Rapport',
            },
        ),
        migrations.AddField(
            model_name='cuveprincipale',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_principales', to='dashboard.site', verbose_name='Site'),
        ),
    ]
