# Generated by Django 5.2.16 on 2026-07-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuvejournaliere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuveprincipale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupeelectrogene',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lignerapport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.AddField(
            model_name='cuvejournaliere',
            name='identifiant',
            field=models.CharField(default='tmp', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuveprincipale',
            name='identifiant',
            field=models.CharField(default='tmp', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupeelectrogene',
            name='identifiant',
            field=models.CharField(default='tmp', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='capacite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='cuve_principale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_journalieres', to='dashboard.cuveprincipale'),
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuveprincipale',
            name='capacite',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cuveprincipale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuveprincipale',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_principales', to='dashboard.site'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='compteur_horaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='consommation_horaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='cuves_journalieres',
            field=models.ManyToManyField(blank=True, related_name='groupes_electrogenes', to='dashboard.cuvejournaliere'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='puissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='compteur_horaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='depotage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='etat_fonctionnement',
            field=models.CharField(default='F', max_length=100),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='quantite_gasoil_cuve_journaliere',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='quantite_gasoil_cuve_principale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dashboard.rapport'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom_site',
            field=models.CharField(max_length=100),
        ),
    ]
