# Generated by Django 6.0.7 on 2026-07-25 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuvejournaliere',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='cuvejournaliere',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='cuveprincipale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='cuveprincipale',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='groupeelectrogene',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='groupeelectrogene',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='lignerapport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='lignerapport',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuveprincipale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='cuve_journaliere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport_cuve_journaliere', to='dashboard.cuvejournaliere'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='cuve_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport_cuve_principale', to='dashboard.cuveprincipale'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapport_groupe', to='dashboard.groupeelectrogene'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
