# Generated by Django 5.2.16 on 2026-07-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cuvejournaliere_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuveprincipale',
            name='site',
        ),
        migrations.RenameField(
            model_name='lignerapport',
            old_name='groupe',
            new_name='groupe_electrogene',
        ),
        migrations.RemoveField(
            model_name='cuvejournaliere',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='groupeelectrogene',
            name='consommation_horaire',
        ),
        migrations.RemoveField(
            model_name='groupeelectrogene',
            name='cuves_journalieres',
        ),
        migrations.AddField(
            model_name='cuvejournaliere',
            name='groupe_electrogene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuve_journaliere', to='dashboard.groupeelectrogene'),
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='capacite',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='cuve_principale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_journaliere', to='dashboard.cuveprincipale'),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='compteur_horaire',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupeelectrogene',
            name='puissance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='compteur_horaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='depotage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='etat_fonctionnement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='quantite_gasoil_cuve_journaliere',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='quantite_gasoil_cuve_principale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
