# Generated by Django 5.2.16 on 2026-07-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cuvejournaliere_id_alter_cuveprincipale_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateurs', to='dashboard.site', verbose_name='Site rattaché'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Opérateur')], default='user', max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='RapportSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('format', models.CharField(default='csv', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], default='success', max_length=20)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions', to='dashboard.rapport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_rapport', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Soumission de rapport',
                'verbose_name_plural': 'Soumissions de rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
